
[tool.isort]
profile = "black"

[tool.black]
line-length = 90
include = '\\.pyi?$'
exclude = '''
/(
    \\.git
  | \\.hg
  | \\.mypy_cache
  | \\.tox
  | \\.env
  | \\.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''
